name: aigc_image_metadata

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: ['3.3.0', stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos
      - run: dart test
      - if: matrix.sdk == '3.3.0'
        run: dart pub downgrade
      - if: matrix.sdk == '3.3.0'
        run: dart test

  coverage-and-publish-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test --coverage=coverage
      - run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
      - run: dart run tool/check_coverage.dart 95
      - run: dart pub publish --dry-run
